### ISSUE TITLE
Interested in new maintainer?

### ISSUE THREAD

**Issue by bnadlerjr** [yuya-takeyama/rack-graphiql#1]
Hi! I was about to write my own Rack based GraphiQL implementation, but decided to do a search first and found this gem. I see that it hasn't been updated in awhile, I'm willing to take it over and maintain it if you want. Would you be interested in giving me maintenance access (or transferring the repo over to me)? I'd also need to be added as an owner on rubygems.org.

**Comment by yuya-takeyama** [comment]
Hi @bnadlerjr,

Thanks for the message.

I am very happy to hear that you want to take over the maintenance of this repo.
I am positive about it.

However, considering the current OSS situation, I think it might be a bad idea to hand over maintenance rights without any consideration.
It is registered on Rubygems.org and seems to have a small number of users.

https://rubygems.org/gems/rack-graphiql
https://github.com/search?q=%22rack-graphiql%22+-user%3Ayuya-takeyama&type=code

So, first of all, could you please send some Pull Requests to this repository?
I'd like to make a decision after seeing them.
Of course, the same goes for ownership of rubygems.org.

Again, thank you for your offer.

**Comment by bnadlerjr** [comment]
Sounds good! I'll make a few pull requests this week.
